services:
  camera-stadion:
    build: .
    container_name: camera-stadion
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - .:/app
    network_mode: host
    # Agar GUI kerak bo'lsa, quyidagilarni oching (Linux uchun):
    # devices:
    #   - "/dev/dri:/dev/dri"
    # privileged: true
    # xhost +local:docker
    # ports:
    #   - "5900:5900"
    #   - "6000:6000"
